### ISSUE TITLE
Following readme instructions does not display the branch switcher in the tool bar

### ISSUE THREAD

**Issue by jessepinuelas** [utarwyn/storybook-branch-switcher#7]
I think I might be missing a step or not understanding the usage correctly. When I run storybook locally after following the read me instructions no branch switcher appears in the storybook tool bar.

### Steps I followed while in beta branch
1. Installed addon via npm i --save-dev storybook-branch-switcher

2. Added storybook branch switcher to my main.js
```
const config = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/addon-toolbars',
    '@storybook/preset-create-react-app',
    'storybook-branch-switcher'
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {
      builder: {
        fsCache: true,
        lazyCompilation: true
      }
    }
  },
  docs: {
    autodocs: 'tag'
  }
};
export default config;
```

3. Created .branches.json in .storybook directory
```
{
  "from": "storybook-static",
  "to": "storybook-bundle",
  "default_branch": "master",
  "default_root": true,
  "script_name": "build-storybook"
}
```

4. Ran **_sb-branch-switcher_** which successfully created storybook-bundle>beta

5. Ran **_npm run storybook_** locally and nothing appeared in the tool bar am I missing something here?

**Comment by jessepinuelas** [comment]
@utarwyn any advice?

**Comment by utarwyn** [comment]
Hello @jessepinuelas, sorry for the response delay.

The script extracts branches only via one of the two providers mentioned in the README ([Bitbucket PRs](https://github.com/utarwyn/storybook-branch-switcher?tab=readme-ov-file#with-bitbucket-opened-prs) or [GitHub PRs](https://github.com/utarwyn/storybook-branch-switcher?tab=readme-ov-file#with-github-opened-prs)) otherwise it will take **only the current branch**. It looks like you can't search for all the existing Git branches.
Is this what you need? Or would you prefer to specify the branches in the configuration file?

**Comment by jessepinuelas** [comment]
@utarwyn When I run storybook locally after following the read me instructions no branch switcher appears in the storybook tool bar.
